feat: add article preview api
unitedforukraine/signpost-template pull request #86
Opened 2022-09-23 12:41 UTC by ishparii

2022-09-23 13:42 UTC, jennytick requested changes

2022-09-23 13:42 UTC, jennytick commented on pages/api/preview.ts
> +async function doesArticleExistAtPath(
This can be moved to signpost-base/zendesk.ts module

2022-09-23 13:42 UTC, jennytick commented on pages/api/preview.ts
> +export default async function handler(
The handler function can also be moved to a new preview module in  signpost-base new and just be called here.

2022-09-23 13:42 UTC, jennytick commented on pages/api/clear-preview-cookies.ts
> +  res.clearPreviewData();
The handler function can also be moved to a new preview module in  signpost-base new and just be called here.

2022-09-23 14:02 UTC, jennytick commented
Also we shall document Preview functionality in README_SITE:
- mention preview token in https://github.com/unitedforukraine/signpost-template/blob/main/README-SITE.md#environment-variables
- link preview mode doc ()https://docs.google.com/document/d/1IbtY_EvIm0c1C8yeKpEPWwPvWJyHiNehYkRpVJJ65kg/edit# in the README

2022-09-23 15:11 UTC, ishparii commented on pages/api/preview.ts
> +async function doesArticleExistAtPath(
done

2022-09-23 15:11 UTC, ishparii commented on pages/api/preview.ts
> +export default async function handler(
Extracted sharable parts

2022-09-23 15:11 UTC, ishparii commented on pages/api/clear-preview-cookies.ts
> +  res.clearPreviewData();
done

2022-09-23 15:12 UTC, ishparii commented
> Also we shall document Preview functionality in README_SITE:
> 
> * mention preview token in https://github.com/unitedforukraine/signpost-template/blob/main/README-SITE.md#environment-variables
> * link preview mode doc ()https://docs.google.com/document/d/1IbtY_EvIm0c1C8yeKpEPWwPvWJyHiNehYkRpVJJ65kg/edit# in the README

added to the doc

2022-09-26 08:15 UTC, jennytick approved these changes

2022-09-26 08:16 UTC, jennytick commented on pages/api/preview.ts
> + * Check https://nextjs.org/docs/advanced-features/preview-mode for explanations.
nit: link https://docs.google.com/document/d/1IbtY_EvIm0c1C8yeKpEPWwPvWJyHiNehYkRpVJJ65kg/edit?usp=sharing here instead of the nextjs preview-mode doc

2022-09-26 09:39 UTC, ishparii commented on pages/api/preview.ts
> + * Check https://nextjs.org/docs/advanced-features/preview-mode for explanations.
done

2022-09-26 09:42 UTC, merged